### ISSUE TITLE
Window buttons seems a bit up

### ISSUE THREAD

**Issue by Adzetko** [Tiamarth/Arc-for-Vivaldi#2]
A screenshot will speak more than a thousand words:
![Vivaldi top bar](https://user-images.githubusercontent.com/18583615/35928952-b0c46cae-0c2e-11e8-8669-d65c0d0aa330.png)
I don't know if this is because I'm running Windows 10, but anyway with the Windows version of Arc I have, the window buttons look like this:
![2018-02-07_17-47-49](https://user-images.githubusercontent.com/18583615/35929118-063b42fc-0c2f-11e8-9f94-a6c0f61f9abb.png)
This might be a padding/margin issue, I think. I don't really know where to look on the CSS file.

**Comment by Tiamarth** [comment]
On Linux, Vivaldi's default window buttons are positioned a bit off compared to Arc's window buttons in other apps, so there's a bit of css at lines 175-182 that repositions them by adjusting their margins. so i'd have to assume Vivaldi's window buttons are positioned differently on different platforms.

I've just changed that bit of css so that it now targets Linux specifically, this should theoretically be fixed now
